# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile

production:
  adapter: postgresql
  encoding: unicode
  database: codeposter_production
  pool: 5
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: codeposter_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: codeposter_test
  pool: 5
  password:
